using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//ejercicio_2
//elquin cascavit
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
////de la pagina project Euler.net

namespace ejercicio_2
{
    class Program
    {
        static void Main(string[] args)
        {

            //variable's declare 
            List<int> x = new List<int>();
            int y,i = 1;
            string out1 = "true";

            //values inicialization
            x.Add(1);
            x.Add(2);
            while (out1 == "true")
            {
                y = x[i - 1] + x[i];
                x.Add(y);

                if(x[i+1] >= 4000000)
                {
                    out1 = "false";
                }
                i++;
            }
            int t1 = 0;
            foreach(int t in x)
            {
               // Console.WriteLine(t);
                if (t %2 == 0)
                {
                    Console.WriteLine(t);
                    t1 = t1 + t;
                }
                 
            }
            Console.WriteLine(t1);


        }

       
    }
}
